@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package jakojaannos.tradingpost.inventory;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;